------------------------------------------------------------------------
-- Storage: images are stored in Cloudflare R2, not Supabase Storage.
-- This migration is intentionally empty — kept for ordering continuity.
-- See wrangler.toml for R2 bucket binding (fundid-item-images).
------------------------------------------------------------------------
