name = "fundid"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-12-01"

[[r2_buckets]]
binding = "ITEM_IMAGES"
bucket_name = "fundid-item-images"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "f9949ac056b542218d932e6c2c7c675e"

[vars]
PUBLIC_IMAGE_BASE_URL = "https://img.fundid.is"
PUBLIC_POSTHOG_KEY = "phc_BxnLWEgef23Khlrx6Q1z9IRkAu2YKNPN39Gf0EceHHJ"
